//Schematic to java Structure by jajo_11 | inspired by "MITHION'S .SCHEMATIC TO JAVA CONVERTINGTOOL"

package net.bvanseghi.starcraft.worldgen.structure;

import java.util.Random;

import net.bvanseghi.starcraft.blocks.ModBlocks;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import net.minecraft.world.gen.feature.WorldGenerator;

public class StructureProtossPylonTemplate extends WorldGenerator {
	protected Block[] GetValidSpawnBlocks() {
		return new Block[] { Blocks.GRASS, Blocks.STONE, Blocks.DIRT, ModBlocks.sandShakuras, ModBlocks.stoneShakuras };
	}
	
	int x = 0;
	int y = 0;
	int z = 0;
	
	public int metaDim;
	public int metaPrimColor;
	public int metaSecColor;
	public Block dimBlock;
	public Block chanBlock;
	public Block stabBlock;

	public boolean LocationIsValidSpawn(World world, BlockPos pos) {
		int distanceToAir = 0;
		Block checkBlock = world.getBlockState(pos.add(x, y, z)).getBlock();

		while (checkBlock != Blocks.AIR) {
			distanceToAir++;
			checkBlock = world.getBlockState(pos.add(x, y + distanceToAir, z)).getBlock();
		}

		if (distanceToAir > 1) {
			return false;
		}

		y += distanceToAir - 1;

		Block block = world.getBlockState(pos).getBlock();
		Material m = block.getBlockState().getBaseState().getMaterial();
		Block blockAbove = world.getBlockState(pos.up()).getBlock();
		Block blockBelow = world.getBlockState(pos.down()).getBlock();

		for (Block i : GetValidSpawnBlocks()) {
			if (blockAbove != Blocks.AIR) {
				return false;
			}
			if (block == i) {
				return true;
			} else if (block == Blocks.SNOW_LAYER && blockBelow == i) {
				return true;
			} else if (m == Material.PLANTS && blockBelow == i) {
				return true;
			}
		}
		return false;
	}

	public boolean generate(int metaPrimColor, int metaSecColor, World world, Random rand, BlockPos pos) {
		this.metaPrimColor = metaPrimColor;
		this.metaSecColor = metaSecColor;
		int i = rand.nextInt(1);

		if (i == 0) {
			generate_r0(world, rand, pos);
		}

		return true;

	}

	public boolean generate_r0(World world, Random rand, BlockPos pos) {
		if (!LocationIsValidSpawn(world, pos) || !LocationIsValidSpawn(world, pos.add(x + 7, y, z))
				|| !LocationIsValidSpawn(world, pos.add(x + 7, y, z + 8)) || !LocationIsValidSpawn(world, pos.add(x, y, z + 8))) {
			return false;
		}

		world.setBlockState(pos.add(x + 0, y + 1, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 1, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 1, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 1, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 1, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 1, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 1, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 1, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 1, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 1, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 1, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 1, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 1, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 1, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 1, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 1, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 1, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 1, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 1, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 1, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 1, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 1, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 1, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 1, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 1, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 1, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 1, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 1, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 1, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 1, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 1, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 1, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 1, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 1, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 1, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 1, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 1, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 1, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 1, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 1, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 1, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 1, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 1, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 1, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 1, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 1, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 1, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 1, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 1, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 1, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 1, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 1, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 1, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 1, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 1, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 1, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 1, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 1, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 1, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 1, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 1, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 1, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 1, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 1, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 1, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 1, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 1, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 1, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 1, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 1, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 1, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 1, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 2, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 2, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 2, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 2, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 2, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 2, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 2, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 2, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 2, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 2, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 2, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 2, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 2, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 2, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 2, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 2, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 2, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 2, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 2, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 2, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 2, z + 2, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 5, y + 2, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 2, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 2, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 2, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 2, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 2, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 2, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 2, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 2, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 2, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 2, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 2, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 2, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 2, z + 4, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 3, y + 2, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 2, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 2, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 2, z + 4, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 7, y + 2, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 2, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 2, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 2, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 2, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 2, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 2, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 2, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 2, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 2, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 2, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 2, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 2, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 2, z + 6, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 5, y + 2, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 2, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 2, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 2, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 2, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 2, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 2, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 2, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 2, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 2, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 2, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 2, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 2, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 2, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 2, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 2, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 2, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 2, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 2, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 3, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 3, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 3, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 3, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 3, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 3, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 3, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 3, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 3, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 3, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 3, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 3, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 3, z + 1, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 5, y + 3, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 3, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 3, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 3, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 3, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 3, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 3, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 3, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 3, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 3, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 3, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 3, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 3, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 3, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 3, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 3, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 3, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 3, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 3, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 3, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 3, z + 4, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 2, y + 3, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 3, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 3, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 3, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 3, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 3, z + 4, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 0, y + 3, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 3, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 3, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 3, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 3, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 3, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 3, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 3, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 3, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 3, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 3, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 3, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 3, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 3, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 3, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 3, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 3, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 3, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 3, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 3, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 3, z + 7, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 5, y + 3, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 3, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 3, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 3, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 3, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 3, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 3, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 3, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 3, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 3, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 3, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 4, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 4, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 4, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 4, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 4, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 4, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 4, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 4, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 4, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 4, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 4, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 4, z + 1, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 4, y + 4, z + 1, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 5, y + 4, z + 1, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 6, y + 4, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 4, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 4, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 4, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 4, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 4, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 4, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 4, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 4, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 4, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 4, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 4, z + 3, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 2, y + 4, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 4, z + 3, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 4, y + 4, z + 3, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 4, z + 3, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 6, y + 4, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 4, z + 3, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 0, y + 4, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 4, z + 4, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 2, y + 4, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 4, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 4, y + 4, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 4, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 6, y + 4, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 4, z + 4, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 0, y + 4, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 4, z + 5, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 2, y + 4, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 4, z + 5, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 4, y + 4, z + 5, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 4, z + 5, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 6, y + 4, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 4, z + 5, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 0, y + 4, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 4, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 4, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 4, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 4, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 4, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 4, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 4, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 4, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 4, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 4, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 4, z + 7, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 4, y + 4, z + 7, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 5, y + 4, z + 7, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 6, y + 4, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 4, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 4, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 4, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 4, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 4, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 4, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 4, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 4, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 4, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 5, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 5, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 5, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 5, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 5, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 5, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 5, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 5, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 5, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 5, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 5, z + 1, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 3, y + 5, z + 1, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 4, y + 5, z + 1, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 5, y + 5, z + 1, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 6, y + 5, z + 1, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 7, y + 5, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 5, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 5, z + 2, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 2, y + 5, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 5, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 5, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 5, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 5, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 5, z + 2, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 0, y + 5, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 5, z + 3, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 2, y + 5, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 5, z + 3, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 4, y + 5, z + 3, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 5, z + 3, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 6, y + 5, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 5, z + 3, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 0, y + 5, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 5, z + 4, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 2, y + 5, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 5, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 4, y + 5, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 5, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 6, y + 5, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 5, z + 4, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 0, y + 5, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 5, z + 5, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 2, y + 5, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 5, z + 5, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 4, y + 5, z + 5, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 5, z + 5, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 6, y + 5, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 5, z + 5, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 0, y + 5, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 5, z + 6, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 2, y + 5, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 5, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 5, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 5, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 5, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 5, z + 6, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 0, y + 5, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 5, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 5, z + 7, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 3, y + 5, z + 7, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 4, y + 5, z + 7, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 5, y + 5, z + 7, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 6, y + 5, z + 7, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 7, y + 5, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 5, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 5, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 5, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 5, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 5, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 5, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 5, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 5, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 6, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 6, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 6, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 6, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 6, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 6, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 6, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 6, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 6, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 6, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 6, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 6, z + 1, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 4, y + 6, z + 1, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 5, y + 6, z + 1, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 6, y + 6, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 6, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 6, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 6, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 6, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 6, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 6, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 6, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 6, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 6, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 6, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 6, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 6, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 6, z + 3, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 4, y + 6, z + 3, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 6, z + 3, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 6, y + 6, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 6, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 6, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 6, z + 4, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 2, y + 6, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 6, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 4, y + 6, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 6, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 6, y + 6, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 6, z + 4, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 0, y + 6, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 6, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 6, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 6, z + 5, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 4, y + 6, z + 5, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 6, z + 5, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 6, y + 6, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 6, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 6, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 6, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 6, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 6, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 6, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 6, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 6, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 6, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 6, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 6, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 6, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 6, z + 7, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 4, y + 6, z + 7, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 5, y + 6, z + 7, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 6, y + 6, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 6, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 6, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 6, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 6, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 6, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 6, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 6, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 6, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 6, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 7, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 7, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 7, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 7, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 7, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 7, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 7, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 7, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 7, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 7, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 7, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 7, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 7, z + 1, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 5, y + 7, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 7, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 7, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 7, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 7, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 7, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 7, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 7, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 7, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 7, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 7, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 7, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 7, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 7, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 7, z + 3, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 4, y + 7, z + 3, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 7, z + 3, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 6, y + 7, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 7, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 7, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 7, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 7, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 7, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 4, y + 7, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 7, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 6, y + 7, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 7, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 7, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 7, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 7, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 7, z + 5, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 4, y + 7, z + 5, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 7, z + 5, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 6, y + 7, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 7, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 7, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 7, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 7, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 7, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 7, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 7, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 7, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 7, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 7, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 7, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 7, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 7, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 7, z + 7, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 5, y + 7, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 7, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 7, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 7, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 7, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 7, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 7, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 7, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 7, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 7, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 7, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 8, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 8, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 8, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 8, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 8, z + 0, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 5, y + 8, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 8, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 8, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 8, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 8, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 8, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 8, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 8, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 8, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 8, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 8, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 8, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 8, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 8, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 8, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 8, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 8, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 8, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 8, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 8, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 8, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 8, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 8, z + 3, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 4, y + 8, z + 3, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 8, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 8, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 8, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 8, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 8, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 8, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 8, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 4, y + 8, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 8, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 6, y + 8, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 8, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 8, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 8, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 8, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 8, z + 5, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 4, y + 8, z + 5, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 8, z + 5, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 6, y + 8, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 8, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 8, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 8, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 8, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 8, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 8, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 8, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 8, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 8, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 8, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 8, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 8, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 8, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 8, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 8, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 8, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 8, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 8, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 8, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 8, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 8, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 8, z + 8, ModBlocks.protossMetal, metaPrimColor, 3);
		world.setBlockState(pos.add(x + 5, y + 8, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 8, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 8, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 9, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 9, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 9, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 9, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 9, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 9, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 9, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 9, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 9, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 9, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 9, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 9, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 9, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 9, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 9, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 9, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 9, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 9, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 9, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 9, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 9, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 9, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 9, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 9, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 9, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 9, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 9, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 9, z + 3, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 4, y + 9, z + 3, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 9, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 9, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 9, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 9, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 9, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 9, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 9, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 4, y + 9, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 9, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 6, y + 9, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 9, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 9, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 9, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 9, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 9, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 9, z + 5, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 9, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 9, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 9, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 9, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 9, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 9, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 9, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 9, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 9, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 9, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 9, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 9, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 9, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 9, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 9, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 9, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 9, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 9, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 9, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 9, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 9, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 9, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 9, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 9, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 9, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 9, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 9, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 10, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 10, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 10, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 10, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 10, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 10, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 10, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 10, z + 0), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 10, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 10, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 10, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 10, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 10, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 10, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 10, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 10, z + 1), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 10, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 10, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 10, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 10, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 10, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 10, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 10, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 10, z + 2), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 10, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 10, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 10, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 10, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 10, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 10, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 10, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 10, z + 3), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 10, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 10, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 10, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 10, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 4, y + 10, z + 4, ModBlocks.crystals, metaSecColor, 3);
		world.setBlockState(pos.add(x + 5, y + 10, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 10, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 10, z + 4), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 10, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 10, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 10, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 10, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 10, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 10, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 10, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 10, z + 5), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 10, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 10, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 10, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 10, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 10, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 10, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 10, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 10, z + 6), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 10, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 10, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 10, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 10, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 10, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 10, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 10, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 10, z + 7), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 0, y + 10, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 1, y + 10, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 2, y + 10, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 3, y + 10, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 4, y + 10, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 5, y + 10, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 6, y + 10, z + 8), Blocks.AIR.getDefaultState());
		world.setBlockState(pos.add(x + 7, y + 10, z + 8), Blocks.AIR.getDefaultState());
		return true;

	}

	@Override
	public boolean generate(World worldIn, Random rand, BlockPos position) {
		// TODO Auto-generated method stub
		return false;
	}

}