// Date: 8/20/2015 9:05:09 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package net.bvanseghi.starcraft.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelLarvaCocoon extends ModelBase {
	// fields
	ModelRenderer eggInner;
	ModelRenderer eggOuter;
	ModelRenderer support1;
	ModelRenderer support2;
	ModelRenderer support3;
	ModelRenderer eggTop;
	ModelRenderer lowerSupport1;
	ModelRenderer lowerSupport2;
	ModelRenderer lowerSupport3;

	public ModelLarvaCocoon() {
		textureWidth = 64;
		textureHeight = 64;

		eggInner = new ModelRenderer(this, 0, 0);
		eggInner.addBox(0F, 0F, 0F, 10, 15, 10);
		eggInner.setRotationPoint(-5F, 9F, -5F);
		eggInner.setTextureSize(64, 32);
		eggInner.mirror = true;
		setRotation(eggInner, 0F, 0F, 0F);
		eggOuter = new ModelRenderer(this, 0, 40);
		eggOuter.addBox(0F, 0F, -6F, 12, 12, 12);
		eggOuter.setRotationPoint(-6F, 11F, 0F);
		eggOuter.setTextureSize(64, 32);
		eggOuter.mirror = true;
		setRotation(eggOuter, 0F, 0F, 0F);
		support1 = new ModelRenderer(this, 40, 0);
		support1.addBox(0F, 0F, 0F, 2, 13, 2);
		support1.setRotationPoint(5F, 10F, -1F);
		support1.setTextureSize(64, 32);
		support1.mirror = true;
		setRotation(support1, 0F, 0F, 0F);
		support2 = new ModelRenderer(this, 40, 0);
		support2.addBox(-0.3F, 0F, 0.1F, 2, 13, 2);
		support2.setRotationPoint(-7F, 10F, -6F);
		support2.setTextureSize(64, 32);
		support2.mirror = true;
		setRotation(support2, 0F, 0.7853982F, 0F);
		support3 = new ModelRenderer(this, 40, 0);
		support3.addBox(-0.6F, 0F, 0.3F, 2, 13, 2);
		support3.setRotationPoint(-7F, 10F, 5F);
		support3.setTextureSize(64, 32);
		support3.mirror = true;
		setRotation(support3, 0F, 0.7853982F, 0F);
		eggTop = new ModelRenderer(this, 0, 25);
		eggTop.addBox(0F, 0F, 0F, 8, 1, 8);
		eggTop.setRotationPoint(-4F, 8F, -4F);
		eggTop.setTextureSize(64, 32);
		eggTop.mirror = true;
		setRotation(eggTop, 0F, 0F, 0F);
		lowerSupport1 = new ModelRenderer(this, 32, 25);
		lowerSupport1.addBox(-0.4F, 0F, 0F, 7, 1, 8);
		lowerSupport1.setRotationPoint(-10F, 23F, 3F);
		lowerSupport1.setTextureSize(64, 32);
		lowerSupport1.mirror = true;
		setRotation(lowerSupport1, 0F, 1.570796F, 0F);
		lowerSupport2 = new ModelRenderer(this, 32, 25);
		lowerSupport2.addBox(0F, 0F, 0F, 7, 1, 8);
		lowerSupport2.setRotationPoint(-3F, 23F, 4F);
		lowerSupport2.setTextureSize(64, 32);
		lowerSupport2.mirror = true;
		setRotation(lowerSupport2, 0F, 0.4363323F, 0F);
		lowerSupport3 = new ModelRenderer(this, 32, 25);
		lowerSupport3.addBox(0F, 0F, 0F, 7, 1, 8);
		lowerSupport3.setRotationPoint(0.3F, 23F, -11F);
		lowerSupport3.setTextureSize(64, 32);
		lowerSupport3.mirror = true;
		setRotation(lowerSupport3, 0F, -0.4363323F, 0F);

	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		eggInner.render(f5);
		eggOuter.render(f5);
		support1.render(f5);
		support2.render(f5);
		support3.render(f5);
		eggTop.render(f5);
		lowerSupport1.render(f5);
		lowerSupport2.render(f5);
		lowerSupport3.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
