// Schematic to java Structure by jajo_11 | inspired by "MITHION'S .SCHEMATIC TO
// JAVA CONVERTINGTOOL"

package ga.scmc.worldgen.structure;

import java.util.Random;

import ga.scmc.blocks.ModBlocks;
import ga.scmc.blocks.metablocks.ModMetaBlocks;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;

public class StructureZergSpawningPool extends SCWorldGenerator {

	@Override
	public boolean generate(World world, Random rand, int offsetX, int offsetY, int offsetZ, BlockPos pos) {
		if(rand.nextInt(1) == 0) {
			generate_r0(world, rand, offsetX, offsetY, offsetZ, pos);
		}

		return true;
	}

	public boolean generate_r0(World world, Random rand, int offsetX, int offsetY, int offsetZ, BlockPos pos) {
		if(!LocationIsValidSpawn(world, pos) || !LocationIsValidSpawn(world, pos.add(18, 0, 0)) || !LocationIsValidSpawn(world, pos.add(18, 0, 20))
				|| !LocationIsValidSpawn(world, pos.add(0, 0, 20))) {
			return false;
		}

		// LogHelper.logger.log(Level.WARN, "Generating pool.");

		// First level
		world.setBlockState(pos.add(8, 0 + offsetY, 1), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 0 + offsetY, 2), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(1, 0 + offsetY, 3), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 0 + offsetY, 3), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 0 + offsetY, 3), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(2, 0 + offsetY, 4), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(3, 0 + offsetY, 4), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 0 + offsetY, 4), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 0 + offsetY, 4), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 0 + offsetY, 4), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 0 + offsetY, 4), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 0 + offsetY, 4), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 0 + offsetY, 4), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 0 + offsetY, 4), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 0 + offsetY, 4), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(15, 0 + offsetY, 4), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 0 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 0 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 0 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 0 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 0 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 0 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 0 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 0 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 0 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 0 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 0 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 0 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 0 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 0 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 0 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 0 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 0 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 0 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 0 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 0 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 0 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 0 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 0 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 0 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 0 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 0 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 0 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 0 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 0 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 0 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 0 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 0 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(3, 0 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 0 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 0 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 0 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 0 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 0 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 0 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 0 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 0 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 0 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 0 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 0 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(15, 0 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(3, 0 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 0 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 0 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 0 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 0 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 0 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 0 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 0 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 0 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 0 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 0 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 0 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(15, 0 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(3, 0 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 0 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 0 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 0 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 0 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 0 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 0 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 0 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 0 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 0 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 0 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 0 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(15, 0 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(3, 0 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 0 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 0 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 0 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 0 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 0 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 0 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 0 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 0 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 0 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 0 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 0 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(15, 0 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(3, 0 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 0 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 0 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 0 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 0 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 0 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 0 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 0 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 0 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 0 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 0 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 0 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(15, 0 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(3, 0 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 0 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 0 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 0 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 0 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 0 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 0 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 0 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 0 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 0 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 0 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 0 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(15, 0 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(3, 0 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 0 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 0 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 0 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 0 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 0 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 0 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 0 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 0 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 0 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 0 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 0 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(15, 0 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(3, 0 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 0 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 0 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 0 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 0 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 0 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 0 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 0 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 0 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 0 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 0 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 0 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(15, 0 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(16, 0 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(18, 0 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(2, 0 + offsetY, 16), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(3, 0 + offsetY, 16), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 0 + offsetY, 16), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 0 + offsetY, 16), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 0 + offsetY, 16), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 0 + offsetY, 16), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 0 + offsetY, 16), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 0 + offsetY, 16), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 0 + offsetY, 16), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 0 + offsetY, 16), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 0 + offsetY, 16), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 0 + offsetY, 16), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 0 + offsetY, 16), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(16, 0 + offsetY, 16), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(17, 0 + offsetY, 16), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(0, 0 + offsetY, 17), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(1, 0 + offsetY, 17), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(3, 0 + offsetY, 17), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 0 + offsetY, 17), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(3, 0 + offsetY, 18), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 0 + offsetY, 18), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 0 + offsetY, 19), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 0 + offsetY, 19), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);

		// Second Level
		world.setBlockState(pos.add(8, 1 + offsetY, 4), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 1 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 1 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 1 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 1 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 1 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 1 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 1 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 1 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 1 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 1 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 1 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 1 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 1 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 1 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 1 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 1 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 1 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 1 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 1 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 1 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 1 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 1 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 1 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 1 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 1 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 1 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 1 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 1 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 1 + offsetY, 8), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 1 + offsetY, 8), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 1 + offsetY, 8), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 1 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 1 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 1 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 1 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 1 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 1 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 1 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 1 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 1 + offsetY, 9), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 1 + offsetY, 9), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 1 + offsetY, 9), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 1 + offsetY, 9), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 1 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 1 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 1 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 1 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 1 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 1 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 1 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 1 + offsetY, 10), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 1 + offsetY, 10), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 1 + offsetY, 10), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 1 + offsetY, 10), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 1 + offsetY, 10), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 1 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 1 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 1 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 1 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 1 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 1 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 1 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 1 + offsetY, 11), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 1 + offsetY, 11), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 1 + offsetY, 11), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 1 + offsetY, 11), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 1 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 1 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 1 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 1 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 1 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 1 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 1 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 1 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 1 + offsetY, 12), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 1 + offsetY, 12), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 1 + offsetY, 12), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 1 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 1 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 1 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 1 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 1 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 1 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 1 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 1 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 1 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 1 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 1 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 1 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 1 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 1 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 1 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 1 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 1 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 1 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 1 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 1 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 1 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 1 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 1 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 1 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 1 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 1 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 1 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 1 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 1 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 1 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 1 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 1 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 1 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 1 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 1 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);

		// Third Level
		world.setBlockState(pos.add(7, 2 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 2 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 2 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 2 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 2 + offsetY, 5), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 2 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 2 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 2 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 2 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 2 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 2 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 2 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 2 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 2 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 2 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 2 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 2 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 2 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 2 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 2 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 2 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 2 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 2 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 2 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 2 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 2 + offsetY, 8), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 2 + offsetY, 8), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 2 + offsetY, 8), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 2 + offsetY, 8), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 2 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 2 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 2 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 2 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 2 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 2 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 2 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 2 + offsetY, 9), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 2 + offsetY, 9), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 2 + offsetY, 9), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 2 + offsetY, 9), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 2 + offsetY, 9), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 2 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 2 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 2 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 2 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 2 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 2 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 2 + offsetY, 10), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 2 + offsetY, 10), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 2 + offsetY, 10), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 2 + offsetY, 10), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 2 + offsetY, 10), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 2 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 2 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 2 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 2 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 2 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 2 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 2 + offsetY, 11), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 2 + offsetY, 11), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 2 + offsetY, 11), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 2 + offsetY, 11), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 2 + offsetY, 11), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 2 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 2 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 2 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 2 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 2 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 2 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 2 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 2 + offsetY, 12), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 2 + offsetY, 12), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 2 + offsetY, 12), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 2 + offsetY, 12), ModBlocks.FLUID_ACID.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 2 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 2 + offsetY, 12), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 2 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 2 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 2 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 2 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 2 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 2 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 2 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 2 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 2 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 2 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 2 + offsetY, 13), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 2 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 2 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 2 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 2 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 2 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 2 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 2 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 2 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 2 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 2 + offsetY, 14), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 2 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 2 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 2 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 2 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 2 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(8, 2 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(9, 2 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(10, 2 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(11, 2 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 2 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 2 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getDefaultState(), 2);

		// Fourth Level
		world.setBlockState(pos.add(5, 3 + offsetY, 6), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 3 + offsetY, 6), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(7, 3 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(8, 3 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(9, 3 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(10, 3 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(11, 3 + offsetY, 6), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(5, 3 + offsetY, 7), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 3 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(12, 3 + offsetY, 7), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(13, 3 + offsetY, 7), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 3 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(13, 3 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(14, 3 + offsetY, 8), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(5, 3 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(13, 3 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(14, 3 + offsetY, 9), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(5, 3 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(13, 3 + offsetY, 10), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(14, 3 + offsetY, 10), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(4, 3 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(5, 3 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(13, 3 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(14, 3 + offsetY, 11), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(4, 3 + offsetY, 12), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 3 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(13, 3 + offsetY, 12), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(4, 3 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(5, 3 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(12, 3 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(13, 3 + offsetY, 13), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 3 + offsetY, 13), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(4, 3 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(5, 3 + offsetY, 14), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 3 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(7, 3 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(8, 3 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(9, 3 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(10, 3 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(11, 3 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(12, 3 + offsetY, 14), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 3 + offsetY, 14), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 3 + offsetY, 14), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(5, 3 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(6, 3 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(12, 3 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);
		world.setBlockState(pos.add(13, 3 + offsetY, 15), ModMetaBlocks.ZERG_FLESH.getStateFromMeta(1), 2);

		// Fifth Level
		world.setBlockState(pos.add(5, 4 + offsetY, 6), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 4 + offsetY, 7), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(14, 4 + offsetY, 10), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(3, 4 + offsetY, 12), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(5, 4 + offsetY, 14), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 4 + offsetY, 14), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);

		// Sixth Level
		world.setBlockState(pos.add(6, 5 + offsetY, 7), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(13, 5 + offsetY, 10), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(6, 5 + offsetY, 13), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		world.setBlockState(pos.add(12, 5 + offsetY, 13), ModBlocks.KERATIN_CHUNK.getDefaultState(), 2);
		return true;
	}

	protected Block[] GetValidSpawnBlocks() {
		return new Block[] { ModBlocks.ZERG_CREEP };
	}

	public boolean LocationIsValidSpawn(World world, BlockPos pos) {

		Block checkBlock = world.getBlockState(pos).getBlock();
		Material m = checkBlock.getDefaultState().getMaterial();
		Block blockAbove = world.getBlockState(pos.up()).getBlock();
		Block blockBelow = world.getBlockState(pos.down()).getBlock();

		for(Block i : GetValidSpawnBlocks()) {
			if(blockAbove != Blocks.AIR) {
				return false;
			}
			if(checkBlock == i) {
				return true;
			} else if(m == Material.PLANTS && blockBelow == i) {
				return true;
			}
		}
		return false;
	}
}